'use client';

import '../Styles/globals.css';
import Script from 'next/script';

import { ThemeProvider } from 'next-themes';
import { NFTProvider } from '../context/NFTContext';

import { Navbar, Footer } from '../components/index';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <NFTProvider>
        <ThemeProvider attribute="class">
          <div className="dark:bg-nft-dark bg-white min-h-screen">
            <Navbar />
            <div className="pt-65">
              {children}
            </div>
            <Footer />
          </div>
          <Script src="https://kit.fontawesome.com/f92bc5c027.js" crossorigin="anonymous" />
        </ThemeProvider>
      </NFTProvider>
    </body>
  </html>
);
export default RootLayout;
